#!/bin/bash

export PATH="./node_modules/.bin:$PATH"

browserify looped.js | uglifyjs > public/looped/bundle.js

browserify carbon-budget.js | uglifyjs > public/carbon-budget/bundle.js
browserify concentration.js | uglifyjs > public/concentration/bundle.js
browserify temperature.js | uglifyjs > public/temperature/bundle.js
browserify from-emissions-to-global-warming.js | uglifyjs > public/from-emissions-to-global-warming/bundle.js
browserify carbon-budget-temperature.js | uglifyjs > public/carbon-budget-temperature/bundle.js
browserify concentration-temperature.js | uglifyjs > public/concentration-temperature/bundle.js
browserify carbon-budget-concentration.js | uglifyjs > public/carbon-budget-concentration/bundle.js

browserify carbon-budget-line-chart.js | uglifyjs > public/carbon-budget-line-chart/bundle.js
browserify concentration-line-chart.js | uglifyjs > public/concentration-line-chart/bundle.js
browserify temperature-line-chart.js | uglifyjs > public/temperature-line-chart/bundle.js
browserify from-emissions-to-global-warming-line-chart.js | uglifyjs > public/from-emissions-to-global-warming-line-chart/bundle.js
browserify carbon-budget-temperature-line-chart.js | uglifyjs > public/carbon-budget-temperature-line-chart/bundle.js
browserify concentration-temperature-line-chart.js | uglifyjs > public/concentration-temperature-line-chart/bundle.js
browserify carbon-budget-concentration-line-chart.js | uglifyjs > public/carbon-budget-concentration-line-chart/bundle.js

node build_html.js

for name in looped carbon-budget temperature concentration from-emissions-to-global-warming carbon-budget-temperature concentration-temperature carbon-budget-concentration carbon-budget-line-chart temperature-line-chart concentration-line-chart from-emissions-to-global-warming-line-chart carbon-budget-temperature-line-chart concentration-temperature-line-chart carbon-budget-concentration-line-chart
do

  rm public/$name/bundle.*.js
  CHECKSUM=($(md5sum public/$name/bundle.js))
  echo $CHECKSUM
  mv public/$name/bundle.js public/$name/bundle.$CHECKSUM.js

  sed -i -e "s/bundle\.js/bundle.$CHECKSUM.js/g" public/$name/index.html

  rsync -avz \
        --delete-delay public/ ../openclimatedata.net/climate-spirals
done
